# Generated by Django 2.2.10 on 2021-04-27 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210427_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_user_id', models.IntegerField()),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('question_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_option_replies', to='survey.QuestionOption')),
            ],
        ),
    ]
